# Generated by Django 5.1.5 on 2025-01-17 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('suspended', 'Приостановлена')], max_length=128)),
                ('logo_url', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('team_members', models.CharField(max_length=2048)),
                ('links', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=128)),
                ('working_status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('suspended', 'Приостановлен')], max_length=128)),
                ('logo_url', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, max_length=1024)),
                ('stack', models.CharField(blank=True, max_length=1024)),
                ('links', models.CharField(blank=True, max_length=1024)),
                ('teams', models.CharField(blank=True, max_length=1024)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount')),
            ],
        ),
    ]
