# Generated by Django 5.1.5 on 2025-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
