# Generated by Django 5.1.5 on 2025-01-26 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_siteprofile_id_alter_useraccount_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='user_id',
        )
    ]
