# Generated by Django 5.1.5 on 2025-01-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_siteprofile_user_id_siteprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='do_search',
            field=models.CharField(blank=True, choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('suspended', 'Приостановлен')], max_length=128),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='id',
            field=models.CharField(max_length=256, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='search_status',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
