# Generated by Django 5.1.5 on 2025-01-26 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_siteprofile_do_search_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.useraccount'),
            preserve_default=False,
        ),
    ]
