# Generated by Django 5.1.5 on 2025-01-26 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_siteprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='siteprofile',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.useraccount'),
            preserve_default=False,
        ),
    ]
