# Generated by Django 5.1.5 on 2025-01-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_siteprofile_user_siteprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteprofile',
            old_name='user_id',
            new_name='person_id',
        ),
    ]
