# Generated by Django 5.1.5 on 2025-01-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_user_id_siteprofile_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteprofile',
            name='person_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
