# Generated by Django 5.1.5 on 2025-01-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_siteprofile_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteprofile',
            name='app_id',
            field=models.CharField(default=None, max_length=256, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
